/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RepairRouteImport } from './routes/repair'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiProcessRouteImport } from './routes/api/process'
import { Route as ApiOutputJobIdFileNameRouteImport } from './routes/api/output/$jobId/$fileName'

const RepairRoute = RepairRouteImport.update({
  id: '/repair',
  path: '/repair',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProcessRoute = ApiProcessRouteImport.update({
  id: '/api/process',
  path: '/api/process',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOutputJobIdFileNameRoute = ApiOutputJobIdFileNameRouteImport.update({
  id: '/api/output/$jobId/$fileName',
  path: '/api/output/$jobId/$fileName',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/repair': typeof RepairRoute
  '/api/process': typeof ApiProcessRoute
  '/api/output/$jobId/$fileName': typeof ApiOutputJobIdFileNameRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/repair': typeof RepairRoute
  '/api/process': typeof ApiProcessRoute
  '/api/output/$jobId/$fileName': typeof ApiOutputJobIdFileNameRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/repair': typeof RepairRoute
  '/api/process': typeof ApiProcessRoute
  '/api/output/$jobId/$fileName': typeof ApiOutputJobIdFileNameRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/repair'
    | '/api/process'
    | '/api/output/$jobId/$fileName'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/repair'
    | '/api/process'
    | '/api/output/$jobId/$fileName'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/repair'
    | '/api/process'
    | '/api/output/$jobId/$fileName'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  RepairRoute: typeof RepairRoute
  ApiProcessRoute: typeof ApiProcessRoute
  ApiOutputJobIdFileNameRoute: typeof ApiOutputJobIdFileNameRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/repair': {
      id: '/repair'
      path: '/repair'
      fullPath: '/repair'
      preLoaderRoute: typeof RepairRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/process': {
      id: '/api/process'
      path: '/api/process'
      fullPath: '/api/process'
      preLoaderRoute: typeof ApiProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/output/$jobId/$fileName': {
      id: '/api/output/$jobId/$fileName'
      path: '/api/output/$jobId/$fileName'
      fullPath: '/api/output/$jobId/$fileName'
      preLoaderRoute: typeof ApiOutputJobIdFileNameRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  RepairRoute: RepairRoute,
  ApiProcessRoute: ApiProcessRoute,
  ApiOutputJobIdFileNameRoute: ApiOutputJobIdFileNameRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
